[package]
name = "fragstrings"
version = "0.1.0"
authors = ["Alex Kordys <akordys@web3tech.ru>"]
edition = "2018"

[dependencies]
format-procmacro = { path = "./format-procmacro" }

[workspace]
members = ["format-procmacro"]
